import {
  AppstoreOutlined,
  ContainerOutlined,
  DesktopOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  PieChartOutlined,
  EllipsisOutlined,
  PicRightOutlined,
  PicLeftOutlined,
  UserOutlined,
  HeartOutlined,
  LikeOutlined,
  StarOutlined,
  GithubOutlined,
  DingdingOutlined,
  WeiboOutlined,
  WechatOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  GoogleOutlined,
} from "@ant-design/icons";

const icons: { [key: string]: any } = {
  AppstoreOutlined,
  ContainerOutlined,
  DesktopOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  PieChartOutlined,
  EllipsisOutlined,
  PicRightOutlined,
  PicLeftOutlined,
  UserOutlined,
  HeartOutlined,
  LikeOutlined,
  StarOutlined,
  GithubOutlined,
  DingdingOutlined,
  WeiboOutlined,
  WechatOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  GoogleOutlined,
};

export default icons;
